### ISSUE TITLE
Why check vs min_dist2 when always stopping at first within threshold?

### ISSUE THREAD

**Issue by drallensmith** [mhauskn/librcsc#4]
https://github.com/mhauskn/librcsc/blob/95d560e3ca52187b401bd3323a967f92072e0623/rcsc/formation/sample_data.cpp#L139

nearestData stops at the first formation that is within the threshold distance (it does not check for the one that's closest; I suspect this is to prevent oscillations). So why bother checking min_dist2?

**Comment by mhauskn** [comment]
Apologies for an unhelpful answer, but having not written librcsc I can't really comment on the reasoning (or lack thereof) behind the existing code...

**Comment by drallensmith** [comment]
I understand; no problem.
